name: Build Infrastructure
#on: ["push"]
on:
    push:
        paths:
            - infrastructure/tf/**
            - .github/workflows/build-infra.yml
jobs:
    build:
        name: Check and deploy terraform
        runs-on: ubuntu-latest
        container: mjkli/terraform-aws:latest # Alpine image with terraform and aws cli on it
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: "us-west-1"
        steps:
            - name: Checkout the repo to the runner
              uses: actions/checkout@v3

            - name: Terraform init
              run: terraform init
              working-directory: infrastructure/tf

            - name: Terraform validate
              run: terraform validate
              id: validate
              working-directory: infrastructure/tf

            - name: Terraform validate status
              if: steps.validate.outcome == 'falure'
              run: exit 1

            - name: Terraform Plan
              id: plan
              run: terraform plan -input=false
              working-directory: infrastructure/tf

            - name: Terraform plan status
              if: steps.plan.outcome == 'falure'
              run: exit 1

            - name: Terrafrom apply
              run: terraform apply -auto-approve -input=false
              working-directory: infrastructure/tf

            - name: wait 2 min for runner to apply
              run: sleep 120