name: Build Infrastructure
on: ["push"]
jobs:
    changes:
      runs-on: ubuntu-latest
      outputs:
        src: ${{ steps.filter.outputs.src }}
        image: ${{ steps.filter.outputs.image }}
      steps:
        - uses: actions/checkout@v3
        - uses: dorny/paths-filter@v2
          id: filter
          with:
              filters: |
                src:
                  - 'api/**'
                image:
                  - 'infrastructure/packer/**'

    image:
        needs: changes
        if: needs.changes.outputs.image == 'true'
        name: Update ami image
        runs-on: ubuntu-latest
        container: mjkli/packer-aws:latest # Alpine image with packer and aws cli on it
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: "us-west-1"
        steps:
            - name: Checkout the repo to the runner
              uses: actions/checkout@v3

            - name: packer init
              run: packer init api_image.pkr.hcl
              working-directory: infrastructure/packer

            - name: packer validate
              run: packer validate .
              working-directory: infrastructure/packer

            - name: packer build
              run: packer build api_image.pkr.hcl
              working-directory: infrastructure/packer

    infra:
        name: Check and deploy terraform
        needs: [image]
        if: ${{ always() }}
        runs-on: ubuntu-latest
        container: mjkli/terraform-aws:latest # Alpine image with terraform and aws cli on it
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: "us-west-1"
        steps:
            - name: Checkout the repo to the runner
              uses: actions/checkout@v3

            - name: Terraform init
              run: terraform init
              working-directory: infrastructure/tf

            - name: Terraform validate
              run: terraform validate
              id: validate
              working-directory: infrastructure/tf

            - name: Terraform validate status
              if: steps.validate.outcome == 'falure'
              run: exit 1

            - name: Terraform Plan
              id: plan
              run: terraform plan -input=false
              working-directory: infrastructure/tf

            - name: Terraform plan status
              if: steps.plan.outcome == 'falure'
              run: exit 1

            - name: Terrafrom apply
              run: terraform apply -auto-approve -input=false
              working-directory: infrastructure/tf

            - name: wait 1 min for runner to apply
              run: sleep 60