name: Build Infrastructure
on: ["push"]
jobs:
    build:
        name: Check and deploy terraform
        runs-on: ubuntu-latest
        container: mjkli/iac-terraform:latest # Alpine image with terraform and aws cli on it
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: "us-west-1"
        steps:
            - name: Checkout the repo to the runner
              uses: actions/checkout@v2

            - name: Terraform init
              run: terraform init
              working-directory: infrastructure/tf

            - name: Terraform validate
              run: terraform validate
              working-directory: infrastructure/tf