name: Build api ami
#on: ["push"]
on:
    push:
        paths:
            - infrastructure/packer/**
jobs:
    build:
        name: Check and deploy terraform
        runs-on: ubuntu-latest
        container: mjkli/packer-aws:latest # Alpine image with terraform and aws cli on it
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: "us-west-1"
        steps:
            - name: Checkout the repo to the runner
              uses: actions/checkout@v3

            - name: packer init
              run: packer init .\api_image.pkr.hcl
              working-directory: infrastructure/packer

            - name: packer validate
              run: packer validate .
              working-directory: infrastructure/packer

            - name: packer build
              run: packer build .\api_image.pkr.hcl
              working-directory: infrastructure/packer
